#!/bin/bash

#Script to output a list of youtube video with their titles from a txt files full of youtube links

# Define input and output files
input_file=$1
output_file=$2

cat "$input_file" | while read line
do
	results=$(yt-dlp --get-title "$line")
	echo "$results - $line"
done > "$output_file"

sort -o "$output_file" "$output_file"
